application: resolute-ascent-849
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
- url: /.*
  script: metasearch.app

libraries:
- name: jinja2
  version: latest